// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyijbrztakhfzitngvug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5aWpicnp0YWtoZnppdG5ndnVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDU3MjYsImV4cCI6MjA3MjM4MTcyNn0.p31dhVOED-bTCMNOmSfFUSjrPPCd0PoxdqVJ60LhVNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});